### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by dawsonbotsford** [BrianNewsom/MetaMonster#2]
How do I install it? I don't use golang so it's not clear

**Comment by BrianNewsom** [comment]
On it. It follows go standards exactly but I'll put some info on installing go itself.    I could also include executables if you'd like that.

**Comment by dawsonbotsford** [comment]
Is it "go get metamonster"? If so that should be in the readme, right?

On Thursday, February 18, 2016, Brian Newsom <notifications@github.com>
wrote:

> On it. It follows go standards exactly but I'll put some info on
> installing go itself. I could also include executables if you'd like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BrianNewsom/MetaMonster/issues/2#issuecomment-185941570>
> .
>


-- 
Dawson Botsford

<http://hackcu.org/>

Dawson Botsford / Director of Operations
dawsonbotsford@gmail.com / 865-804-9305


HackCU.org <http://hackcu.org/>

[image: LinkedIn]
<https://www.linkedin.com/profile/view?id=354626699&trk=nav_responsive_tab_profile_pic>
 [image: Github] <http://github.com/dawsonbotsford> [image: Twitter]
<http://twitter.com/dawsonbotsford>

**Comment by BrianNewsom** [comment]
If you have go, try
```
go install github.com/briannewsom/metamonster
```

If that doesn't work for you let me know! This has been added to the README, thanks!
